# -*- coding: utf-8 -*-
"""map.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x3Hes15tpBKKpBoZmhv4nShi8jVXwyRT
"""

#map
mylist=[10,20,30]
def square(num):
  return num**2
list(map(square,mylist))

#exceptional handling
#try==>code to run
#except==>error occurs
#finally==>
try:
  print(10)
  print(num123)
except (NameError,TypeError) as e:
  print("error occured",e)
except Exception as e:
  print("all error occured",e)
finally:
  print("hey")

s="egg"
t="add"
mydict_s={}
for i in range(0,len(s)):
  if s[i] in mydict_s and mydict_s[s[i]]!=t[i]:
    print("not isomorphic")
  else:
    mydict_s[s[i]]=t[i]
    print(mydict_s)